// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playerdata.proto

package monopoly.protobuffer;

public final class PlayerDataProto {
  private PlayerDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:monopoly.protobuffer.Player)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 token = 2;</code>
     */
    boolean hasToken();
    /**
     * <code>required int32 token = 2;</code>
     */
    int getToken();

    /**
     * <code>required bool ai = 3;</code>
     */
    boolean hasAi();
    /**
     * <code>required bool ai = 3;</code>
     */
    boolean getAi();

    /**
     * <code>required int32 money = 4;</code>
     */
    boolean hasMoney();
    /**
     * <code>required int32 money = 4;</code>
     */
    int getMoney();

    /**
     * <code>required int32 location = 5;</code>
     */
    boolean hasLocation();
    /**
     * <code>required int32 location = 5;</code>
     */
    int getLocation();

    /**
     * <code>required int32 jail_free_cards = 6;</code>
     */
    boolean hasJailFreeCards();
    /**
     * <code>required int32 jail_free_cards = 6;</code>
     */
    int getJailFreeCards();

    /**
     * <code>required bool in_jail = 7;</code>
     */
    boolean hasInJail();
    /**
     * <code>required bool in_jail = 7;</code>
     */
    boolean getInJail();
  }
  /**
   * Protobuf type {@code monopoly.protobuffer.Player}
   */
  public static final class Player extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:monopoly.protobuffer.Player)
      PlayerOrBuilder {
    // Use Player.newBuilder() to construct.
    private Player(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Player(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Player defaultInstance;
    public static Player getDefaultInstance() {
      return defaultInstance;
    }

    public Player getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Player(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              token_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              ai_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              money_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              location_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              jailFreeCards_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              inJail_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return monopoly.protobuffer.PlayerDataProto.internal_static_monopoly_protobuffer_Player_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return monopoly.protobuffer.PlayerDataProto.internal_static_monopoly_protobuffer_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              monopoly.protobuffer.PlayerDataProto.Player.class, monopoly.protobuffer.PlayerDataProto.Player.Builder.class);
    }

    public static com.google.protobuf.Parser<Player> PARSER =
        new com.google.protobuf.AbstractParser<Player>() {
      public Player parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Player(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Player> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private int token_;
    /**
     * <code>required int32 token = 2;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 token = 2;</code>
     */
    public int getToken() {
      return token_;
    }

    public static final int AI_FIELD_NUMBER = 3;
    private boolean ai_;
    /**
     * <code>required bool ai = 3;</code>
     */
    public boolean hasAi() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool ai = 3;</code>
     */
    public boolean getAi() {
      return ai_;
    }

    public static final int MONEY_FIELD_NUMBER = 4;
    private int money_;
    /**
     * <code>required int32 money = 4;</code>
     */
    public boolean hasMoney() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 money = 4;</code>
     */
    public int getMoney() {
      return money_;
    }

    public static final int LOCATION_FIELD_NUMBER = 5;
    private int location_;
    /**
     * <code>required int32 location = 5;</code>
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 location = 5;</code>
     */
    public int getLocation() {
      return location_;
    }

    public static final int JAIL_FREE_CARDS_FIELD_NUMBER = 6;
    private int jailFreeCards_;
    /**
     * <code>required int32 jail_free_cards = 6;</code>
     */
    public boolean hasJailFreeCards() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 jail_free_cards = 6;</code>
     */
    public int getJailFreeCards() {
      return jailFreeCards_;
    }

    public static final int IN_JAIL_FIELD_NUMBER = 7;
    private boolean inJail_;
    /**
     * <code>required bool in_jail = 7;</code>
     */
    public boolean hasInJail() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required bool in_jail = 7;</code>
     */
    public boolean getInJail() {
      return inJail_;
    }

    private void initFields() {
      name_ = "";
      token_ = 0;
      ai_ = false;
      money_ = 0;
      location_ = 0;
      jailFreeCards_ = 0;
      inJail_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAi()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMoney()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJailFreeCards()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInJail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, token_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, ai_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, money_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, location_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, jailFreeCards_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, inJail_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, token_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, ai_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, money_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, location_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, jailFreeCards_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, inJail_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static monopoly.protobuffer.PlayerDataProto.Player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monopoly.protobuffer.PlayerDataProto.Player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monopoly.protobuffer.PlayerDataProto.Player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monopoly.protobuffer.PlayerDataProto.Player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monopoly.protobuffer.PlayerDataProto.Player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static monopoly.protobuffer.PlayerDataProto.Player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static monopoly.protobuffer.PlayerDataProto.Player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static monopoly.protobuffer.PlayerDataProto.Player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static monopoly.protobuffer.PlayerDataProto.Player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static monopoly.protobuffer.PlayerDataProto.Player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(monopoly.protobuffer.PlayerDataProto.Player prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code monopoly.protobuffer.Player}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:monopoly.protobuffer.Player)
        monopoly.protobuffer.PlayerDataProto.PlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return monopoly.protobuffer.PlayerDataProto.internal_static_monopoly_protobuffer_Player_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return monopoly.protobuffer.PlayerDataProto.internal_static_monopoly_protobuffer_Player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                monopoly.protobuffer.PlayerDataProto.Player.class, monopoly.protobuffer.PlayerDataProto.Player.Builder.class);
      }

      // Construct using monopoly.protobuffer.PlayerDataProto.Player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        ai_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        money_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        location_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        jailFreeCards_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        inJail_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return monopoly.protobuffer.PlayerDataProto.internal_static_monopoly_protobuffer_Player_descriptor;
      }

      public monopoly.protobuffer.PlayerDataProto.Player getDefaultInstanceForType() {
        return monopoly.protobuffer.PlayerDataProto.Player.getDefaultInstance();
      }

      public monopoly.protobuffer.PlayerDataProto.Player build() {
        monopoly.protobuffer.PlayerDataProto.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public monopoly.protobuffer.PlayerDataProto.Player buildPartial() {
        monopoly.protobuffer.PlayerDataProto.Player result = new monopoly.protobuffer.PlayerDataProto.Player(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ai_ = ai_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.money_ = money_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.location_ = location_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.jailFreeCards_ = jailFreeCards_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.inJail_ = inJail_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof monopoly.protobuffer.PlayerDataProto.Player) {
          return mergeFrom((monopoly.protobuffer.PlayerDataProto.Player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(monopoly.protobuffer.PlayerDataProto.Player other) {
        if (other == monopoly.protobuffer.PlayerDataProto.Player.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasAi()) {
          setAi(other.getAi());
        }
        if (other.hasMoney()) {
          setMoney(other.getMoney());
        }
        if (other.hasLocation()) {
          setLocation(other.getLocation());
        }
        if (other.hasJailFreeCards()) {
          setJailFreeCards(other.getJailFreeCards());
        }
        if (other.hasInJail()) {
          setInJail(other.getInJail());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasToken()) {
          
          return false;
        }
        if (!hasAi()) {
          
          return false;
        }
        if (!hasMoney()) {
          
          return false;
        }
        if (!hasLocation()) {
          
          return false;
        }
        if (!hasJailFreeCards()) {
          
          return false;
        }
        if (!hasInJail()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        monopoly.protobuffer.PlayerDataProto.Player parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (monopoly.protobuffer.PlayerDataProto.Player) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int token_ ;
      /**
       * <code>required int32 token = 2;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 token = 2;</code>
       */
      public int getToken() {
        return token_;
      }
      /**
       * <code>required int32 token = 2;</code>
       */
      public Builder setToken(int value) {
        bitField0_ |= 0x00000002;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 token = 2;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = 0;
        onChanged();
        return this;
      }

      private boolean ai_ ;
      /**
       * <code>required bool ai = 3;</code>
       */
      public boolean hasAi() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool ai = 3;</code>
       */
      public boolean getAi() {
        return ai_;
      }
      /**
       * <code>required bool ai = 3;</code>
       */
      public Builder setAi(boolean value) {
        bitField0_ |= 0x00000004;
        ai_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool ai = 3;</code>
       */
      public Builder clearAi() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ai_ = false;
        onChanged();
        return this;
      }

      private int money_ ;
      /**
       * <code>required int32 money = 4;</code>
       */
      public boolean hasMoney() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 money = 4;</code>
       */
      public int getMoney() {
        return money_;
      }
      /**
       * <code>required int32 money = 4;</code>
       */
      public Builder setMoney(int value) {
        bitField0_ |= 0x00000008;
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 money = 4;</code>
       */
      public Builder clearMoney() {
        bitField0_ = (bitField0_ & ~0x00000008);
        money_ = 0;
        onChanged();
        return this;
      }

      private int location_ ;
      /**
       * <code>required int32 location = 5;</code>
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 location = 5;</code>
       */
      public int getLocation() {
        return location_;
      }
      /**
       * <code>required int32 location = 5;</code>
       */
      public Builder setLocation(int value) {
        bitField0_ |= 0x00000010;
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 location = 5;</code>
       */
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000010);
        location_ = 0;
        onChanged();
        return this;
      }

      private int jailFreeCards_ ;
      /**
       * <code>required int32 jail_free_cards = 6;</code>
       */
      public boolean hasJailFreeCards() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 jail_free_cards = 6;</code>
       */
      public int getJailFreeCards() {
        return jailFreeCards_;
      }
      /**
       * <code>required int32 jail_free_cards = 6;</code>
       */
      public Builder setJailFreeCards(int value) {
        bitField0_ |= 0x00000020;
        jailFreeCards_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 jail_free_cards = 6;</code>
       */
      public Builder clearJailFreeCards() {
        bitField0_ = (bitField0_ & ~0x00000020);
        jailFreeCards_ = 0;
        onChanged();
        return this;
      }

      private boolean inJail_ ;
      /**
       * <code>required bool in_jail = 7;</code>
       */
      public boolean hasInJail() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required bool in_jail = 7;</code>
       */
      public boolean getInJail() {
        return inJail_;
      }
      /**
       * <code>required bool in_jail = 7;</code>
       */
      public Builder setInJail(boolean value) {
        bitField0_ |= 0x00000040;
        inJail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool in_jail = 7;</code>
       */
      public Builder clearInJail() {
        bitField0_ = (bitField0_ & ~0x00000040);
        inJail_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:monopoly.protobuffer.Player)
    }

    static {
      defaultInstance = new Player(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:monopoly.protobuffer.Player)
  }

  public interface PlayerListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:monopoly.protobuffer.PlayerList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
     */
    java.util.List<monopoly.protobuffer.PlayerDataProto.Player> 
        getPList();
    /**
     * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
     */
    monopoly.protobuffer.PlayerDataProto.Player getP(int index);
    /**
     * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
     */
    int getPCount();
    /**
     * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
     */
    java.util.List<? extends monopoly.protobuffer.PlayerDataProto.PlayerOrBuilder> 
        getPOrBuilderList();
    /**
     * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
     */
    monopoly.protobuffer.PlayerDataProto.PlayerOrBuilder getPOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code monopoly.protobuffer.PlayerList}
   */
  public static final class PlayerList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:monopoly.protobuffer.PlayerList)
      PlayerListOrBuilder {
    // Use PlayerList.newBuilder() to construct.
    private PlayerList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerList defaultInstance;
    public static PlayerList getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                p_ = new java.util.ArrayList<monopoly.protobuffer.PlayerDataProto.Player>();
                mutable_bitField0_ |= 0x00000001;
              }
              p_.add(input.readMessage(monopoly.protobuffer.PlayerDataProto.Player.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          p_ = java.util.Collections.unmodifiableList(p_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return monopoly.protobuffer.PlayerDataProto.internal_static_monopoly_protobuffer_PlayerList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return monopoly.protobuffer.PlayerDataProto.internal_static_monopoly_protobuffer_PlayerList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              monopoly.protobuffer.PlayerDataProto.PlayerList.class, monopoly.protobuffer.PlayerDataProto.PlayerList.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerList> PARSER =
        new com.google.protobuf.AbstractParser<PlayerList>() {
      public PlayerList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerList> getParserForType() {
      return PARSER;
    }

    public static final int P_FIELD_NUMBER = 1;
    private java.util.List<monopoly.protobuffer.PlayerDataProto.Player> p_;
    /**
     * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
     */
    public java.util.List<monopoly.protobuffer.PlayerDataProto.Player> getPList() {
      return p_;
    }
    /**
     * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
     */
    public java.util.List<? extends monopoly.protobuffer.PlayerDataProto.PlayerOrBuilder> 
        getPOrBuilderList() {
      return p_;
    }
    /**
     * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
     */
    public int getPCount() {
      return p_.size();
    }
    /**
     * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
     */
    public monopoly.protobuffer.PlayerDataProto.Player getP(int index) {
      return p_.get(index);
    }
    /**
     * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
     */
    public monopoly.protobuffer.PlayerDataProto.PlayerOrBuilder getPOrBuilder(
        int index) {
      return p_.get(index);
    }

    private void initFields() {
      p_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPCount(); i++) {
        if (!getP(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < p_.size(); i++) {
        output.writeMessage(1, p_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < p_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, p_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static monopoly.protobuffer.PlayerDataProto.PlayerList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monopoly.protobuffer.PlayerDataProto.PlayerList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monopoly.protobuffer.PlayerDataProto.PlayerList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monopoly.protobuffer.PlayerDataProto.PlayerList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monopoly.protobuffer.PlayerDataProto.PlayerList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static monopoly.protobuffer.PlayerDataProto.PlayerList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static monopoly.protobuffer.PlayerDataProto.PlayerList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static monopoly.protobuffer.PlayerDataProto.PlayerList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static monopoly.protobuffer.PlayerDataProto.PlayerList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static monopoly.protobuffer.PlayerDataProto.PlayerList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(monopoly.protobuffer.PlayerDataProto.PlayerList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code monopoly.protobuffer.PlayerList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:monopoly.protobuffer.PlayerList)
        monopoly.protobuffer.PlayerDataProto.PlayerListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return monopoly.protobuffer.PlayerDataProto.internal_static_monopoly_protobuffer_PlayerList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return monopoly.protobuffer.PlayerDataProto.internal_static_monopoly_protobuffer_PlayerList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                monopoly.protobuffer.PlayerDataProto.PlayerList.class, monopoly.protobuffer.PlayerDataProto.PlayerList.Builder.class);
      }

      // Construct using monopoly.protobuffer.PlayerDataProto.PlayerList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pBuilder_ == null) {
          p_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return monopoly.protobuffer.PlayerDataProto.internal_static_monopoly_protobuffer_PlayerList_descriptor;
      }

      public monopoly.protobuffer.PlayerDataProto.PlayerList getDefaultInstanceForType() {
        return monopoly.protobuffer.PlayerDataProto.PlayerList.getDefaultInstance();
      }

      public monopoly.protobuffer.PlayerDataProto.PlayerList build() {
        monopoly.protobuffer.PlayerDataProto.PlayerList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public monopoly.protobuffer.PlayerDataProto.PlayerList buildPartial() {
        monopoly.protobuffer.PlayerDataProto.PlayerList result = new monopoly.protobuffer.PlayerDataProto.PlayerList(this);
        int from_bitField0_ = bitField0_;
        if (pBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            p_ = java.util.Collections.unmodifiableList(p_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.p_ = p_;
        } else {
          result.p_ = pBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof monopoly.protobuffer.PlayerDataProto.PlayerList) {
          return mergeFrom((monopoly.protobuffer.PlayerDataProto.PlayerList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(monopoly.protobuffer.PlayerDataProto.PlayerList other) {
        if (other == monopoly.protobuffer.PlayerDataProto.PlayerList.getDefaultInstance()) return this;
        if (pBuilder_ == null) {
          if (!other.p_.isEmpty()) {
            if (p_.isEmpty()) {
              p_ = other.p_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePIsMutable();
              p_.addAll(other.p_);
            }
            onChanged();
          }
        } else {
          if (!other.p_.isEmpty()) {
            if (pBuilder_.isEmpty()) {
              pBuilder_.dispose();
              pBuilder_ = null;
              p_ = other.p_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPFieldBuilder() : null;
            } else {
              pBuilder_.addAllMessages(other.p_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPCount(); i++) {
          if (!getP(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        monopoly.protobuffer.PlayerDataProto.PlayerList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (monopoly.protobuffer.PlayerDataProto.PlayerList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<monopoly.protobuffer.PlayerDataProto.Player> p_ =
        java.util.Collections.emptyList();
      private void ensurePIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          p_ = new java.util.ArrayList<monopoly.protobuffer.PlayerDataProto.Player>(p_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          monopoly.protobuffer.PlayerDataProto.Player, monopoly.protobuffer.PlayerDataProto.Player.Builder, monopoly.protobuffer.PlayerDataProto.PlayerOrBuilder> pBuilder_;

      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public java.util.List<monopoly.protobuffer.PlayerDataProto.Player> getPList() {
        if (pBuilder_ == null) {
          return java.util.Collections.unmodifiableList(p_);
        } else {
          return pBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public int getPCount() {
        if (pBuilder_ == null) {
          return p_.size();
        } else {
          return pBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public monopoly.protobuffer.PlayerDataProto.Player getP(int index) {
        if (pBuilder_ == null) {
          return p_.get(index);
        } else {
          return pBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public Builder setP(
          int index, monopoly.protobuffer.PlayerDataProto.Player value) {
        if (pBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePIsMutable();
          p_.set(index, value);
          onChanged();
        } else {
          pBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public Builder setP(
          int index, monopoly.protobuffer.PlayerDataProto.Player.Builder builderForValue) {
        if (pBuilder_ == null) {
          ensurePIsMutable();
          p_.set(index, builderForValue.build());
          onChanged();
        } else {
          pBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public Builder addP(monopoly.protobuffer.PlayerDataProto.Player value) {
        if (pBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePIsMutable();
          p_.add(value);
          onChanged();
        } else {
          pBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public Builder addP(
          int index, monopoly.protobuffer.PlayerDataProto.Player value) {
        if (pBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePIsMutable();
          p_.add(index, value);
          onChanged();
        } else {
          pBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public Builder addP(
          monopoly.protobuffer.PlayerDataProto.Player.Builder builderForValue) {
        if (pBuilder_ == null) {
          ensurePIsMutable();
          p_.add(builderForValue.build());
          onChanged();
        } else {
          pBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public Builder addP(
          int index, monopoly.protobuffer.PlayerDataProto.Player.Builder builderForValue) {
        if (pBuilder_ == null) {
          ensurePIsMutable();
          p_.add(index, builderForValue.build());
          onChanged();
        } else {
          pBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public Builder addAllP(
          java.lang.Iterable<? extends monopoly.protobuffer.PlayerDataProto.Player> values) {
        if (pBuilder_ == null) {
          ensurePIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, p_);
          onChanged();
        } else {
          pBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public Builder clearP() {
        if (pBuilder_ == null) {
          p_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public Builder removeP(int index) {
        if (pBuilder_ == null) {
          ensurePIsMutable();
          p_.remove(index);
          onChanged();
        } else {
          pBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public monopoly.protobuffer.PlayerDataProto.Player.Builder getPBuilder(
          int index) {
        return getPFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public monopoly.protobuffer.PlayerDataProto.PlayerOrBuilder getPOrBuilder(
          int index) {
        if (pBuilder_ == null) {
          return p_.get(index);  } else {
          return pBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public java.util.List<? extends monopoly.protobuffer.PlayerDataProto.PlayerOrBuilder> 
           getPOrBuilderList() {
        if (pBuilder_ != null) {
          return pBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(p_);
        }
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public monopoly.protobuffer.PlayerDataProto.Player.Builder addPBuilder() {
        return getPFieldBuilder().addBuilder(
            monopoly.protobuffer.PlayerDataProto.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public monopoly.protobuffer.PlayerDataProto.Player.Builder addPBuilder(
          int index) {
        return getPFieldBuilder().addBuilder(
            index, monopoly.protobuffer.PlayerDataProto.Player.getDefaultInstance());
      }
      /**
       * <code>repeated .monopoly.protobuffer.Player p = 1;</code>
       */
      public java.util.List<monopoly.protobuffer.PlayerDataProto.Player.Builder> 
           getPBuilderList() {
        return getPFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          monopoly.protobuffer.PlayerDataProto.Player, monopoly.protobuffer.PlayerDataProto.Player.Builder, monopoly.protobuffer.PlayerDataProto.PlayerOrBuilder> 
          getPFieldBuilder() {
        if (pBuilder_ == null) {
          pBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              monopoly.protobuffer.PlayerDataProto.Player, monopoly.protobuffer.PlayerDataProto.Player.Builder, monopoly.protobuffer.PlayerDataProto.PlayerOrBuilder>(
                  p_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          p_ = null;
        }
        return pBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:monopoly.protobuffer.PlayerList)
    }

    static {
      defaultInstance = new PlayerList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:monopoly.protobuffer.PlayerList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monopoly_protobuffer_Player_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monopoly_protobuffer_Player_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_monopoly_protobuffer_PlayerList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_monopoly_protobuffer_PlayerList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020playerdata.proto\022\024monopoly.protobuffer" +
      "\"|\n\006Player\022\014\n\004name\030\001 \002(\t\022\r\n\005token\030\002 \002(\005\022" +
      "\n\n\002ai\030\003 \002(\010\022\r\n\005money\030\004 \002(\005\022\020\n\010location\030\005" +
      " \002(\005\022\027\n\017jail_free_cards\030\006 \002(\005\022\017\n\007in_jail" +
      "\030\007 \002(\010\"5\n\nPlayerList\022\'\n\001p\030\001 \003(\0132\034.monopo" +
      "ly.protobuffer.PlayerB\021B\017PlayerDataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_monopoly_protobuffer_Player_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_monopoly_protobuffer_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monopoly_protobuffer_Player_descriptor,
        new java.lang.String[] { "Name", "Token", "Ai", "Money", "Location", "JailFreeCards", "InJail", });
    internal_static_monopoly_protobuffer_PlayerList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_monopoly_protobuffer_PlayerList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_monopoly_protobuffer_PlayerList_descriptor,
        new java.lang.String[] { "P", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
