/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopoly.gui;

import javax.swing.JButton;
import monopoly.Game;

/**
 *
 * The board for the GUI
 */
public class Board extends javax.swing.JFrame {
    
    
    public JButton[] grid_buttons;
    
    final int BOARDSIZE = 40;
    /**
     * Creates new form board
     */
    public Board() {
        
        initComponents();
        makeGridButtonsArray();
        initDie();
        initBoard();
        initMenu();
    }
    
    private void initBoard() {
        makeGridButtonsArray();
        Game.grid_controller.addButtons(grid_buttons);
        Game.object_controller.addObjectLayer(Objects);
        Game.object_controller.initPlayers();
        
    }
    private void makeGridButtonsArray() {
        grid_buttons = new JButton[BOARDSIZE];
        grid_buttons[0] = Go;
        grid_buttons[1] = Mediterranean;
        grid_buttons[2] = CommunityChest1;
        grid_buttons[3] = Baltic;
        grid_buttons[4] = IncomeTax;
        grid_buttons[5] = Reading;
        grid_buttons[6] = Oriental;
        grid_buttons[7] = Chance1;
        grid_buttons[8] = Vermont;
        grid_buttons[9] = Connecticut;
        grid_buttons[10] = Jail;
        grid_buttons[11] = Charles;
        grid_buttons[12] = Electric;
        grid_buttons[13] = States;
        grid_buttons[14] = Virginia;
        grid_buttons[15] = PennisylvaniaRR;
        grid_buttons[16] = James;
        grid_buttons[17] = CommunityChest2;
        grid_buttons[18] = Tenessee;
        grid_buttons[19] = NewYork;
        grid_buttons[20] = FreeParking;
        grid_buttons[21] = Kentucky;
        grid_buttons[22] = Chance2;
        grid_buttons[23] = Indiana;
        grid_buttons[24] = Illonois;
        grid_buttons[25] = BO;
        grid_buttons[26] = Atlantic;
        grid_buttons[27] = Ventinor;
        grid_buttons[28] = WaterWorks;
        grid_buttons[29] = Marvin;
        grid_buttons[30] = GoToJail;
        grid_buttons[31] = Pacific;
        grid_buttons[32] = NorthCarolina;
        grid_buttons[33] = CommunityChest3;
        grid_buttons[34] = Pennisylvania;
        grid_buttons[35] = Short;
        grid_buttons[36] = Chance3;
        grid_buttons[37] = ParkPlace;
        grid_buttons[38] = LuxuryTax;
        grid_buttons[39] = Boardwalk;
        for (JButton b: grid_buttons) {
            b.addActionListener(Game.grid_controller);
        }
    }
                
    
    private void initDie() {
        Game.dice_controller.addButtons(Die1,Die2);
        Die1.addActionListener(Game.dice_controller);
        Die2.addActionListener(Game.dice_controller);
    }
    
    private void initMenu() {
        Game.menu_controller.initMenu(Menu);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Layers = new javax.swing.JLayeredPane();
        Objects = new javax.swing.JPanel();
        Die2 = new javax.swing.JButton();
        Die1 = new javax.swing.JButton();
        Board = new javax.swing.JPanel();
        south = new javax.swing.JPanel();
        Jail = new javax.swing.JButton();
        Go = new javax.swing.JButton();
        Mediterranean = new javax.swing.JButton();
        CommunityChest1 = new javax.swing.JButton();
        Baltic = new javax.swing.JButton();
        IncomeTax = new javax.swing.JButton();
        Reading = new javax.swing.JButton();
        Oriental = new javax.swing.JButton();
        Chance1 = new javax.swing.JButton();
        Vermont = new javax.swing.JButton();
        Connecticut = new javax.swing.JButton();
        west = new javax.swing.JPanel();
        Tenessee = new javax.swing.JButton();
        CommunityChest2 = new javax.swing.JButton();
        James = new javax.swing.JButton();
        PennisylvaniaRR = new javax.swing.JButton();
        States = new javax.swing.JButton();
        Virginia = new javax.swing.JButton();
        Electric = new javax.swing.JButton();
        Charles = new javax.swing.JButton();
        NewYork = new javax.swing.JButton();
        east = new javax.swing.JPanel();
        Pacific = new javax.swing.JButton();
        NorthCarolina = new javax.swing.JButton();
        CommunityChest3 = new javax.swing.JButton();
        Pennisylvania = new javax.swing.JButton();
        Short = new javax.swing.JButton();
        Chance3 = new javax.swing.JButton();
        ParkPlace = new javax.swing.JButton();
        LuxuryTax = new javax.swing.JButton();
        Boardwalk = new javax.swing.JButton();
        center = new javax.swing.JPanel();
        centerBoard = new javax.swing.JLabel();
        north = new javax.swing.JPanel();
        FreeParking = new javax.swing.JButton();
        GoToJail = new javax.swing.JButton();
        Kentucky = new javax.swing.JButton();
        Chance2 = new javax.swing.JButton();
        Indiana = new javax.swing.JButton();
        Illonois = new javax.swing.JButton();
        BO = new javax.swing.JButton();
        Atlantic = new javax.swing.JButton();
        Marvin = new javax.swing.JButton();
        WaterWorks = new javax.swing.JButton();
        Ventinor = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1320, 1020));
        setMinimumSize(new java.awt.Dimension(1320, 1020));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Layers.setPreferredSize(new java.awt.Dimension(1020, 1020));

        Objects.setMaximumSize(new java.awt.Dimension(1020, 1020));
        Objects.setOpaque(false);
        Objects.setPreferredSize(new java.awt.Dimension(1020, 1020));
        Objects.setLayout(null);

        Die2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/dice/dice1.png"))); // NOI18N
        Die2.setBorder(null);
        Die2.setBorderPainted(false);
        Die2.setContentAreaFilled(false);
        Objects.add(Die2);
        Die2.setBounds(390, 470, 100, 110);

        Die1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/dice/dice1.png"))); // NOI18N
        Die1.setBorder(null);
        Die1.setBorderPainted(false);
        Die1.setContentAreaFilled(false);
        Objects.add(Die1);
        Die1.setBounds(510, 470, 100, 110);

        Layers.setLayer(Objects, javax.swing.JLayeredPane.PALETTE_LAYER);
        Layers.add(Objects);
        Objects.setBounds(0, 0, 1020, 1020);

        Board.setMaximumSize(new java.awt.Dimension(1020, 1020));
        Board.setMinimumSize(new java.awt.Dimension(1020, 1020));
        Board.setLayout(new java.awt.BorderLayout());

        south.setBackground(java.awt.Color.darkGray);
        south.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        south.setName("south"); // NOI18N
        south.setPreferredSize(new java.awt.Dimension(1020, 150));
        south.setLayout(new java.awt.GridBagLayout());

        Jail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/jail.jpg"))); // NOI18N
        Jail.setBorder(null);
        Jail.setPreferredSize(new java.awt.Dimension(150, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        south.add(Jail, gridBagConstraints);

        Go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/go.jpg"))); // NOI18N
        Go.setBorder(null);
        Go.setBorderPainted(false);
        Go.setMaximumSize(new java.awt.Dimension(150, 150));
        Go.setMinimumSize(new java.awt.Dimension(150, 150));
        Go.setPreferredSize(new java.awt.Dimension(150, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        south.add(Go, gridBagConstraints);

        Mediterranean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/mediterranean.jpg"))); // NOI18N
        Mediterranean.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Mediterranean.setMaximumSize(new java.awt.Dimension(80, 150));
        Mediterranean.setMinimumSize(new java.awt.Dimension(80, 150));
        Mediterranean.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        south.add(Mediterranean, gridBagConstraints);

        CommunityChest1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/communitchestsouth.jpg"))); // NOI18N
        CommunityChest1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CommunityChest1.setMaximumSize(new java.awt.Dimension(80, 150));
        CommunityChest1.setMinimumSize(new java.awt.Dimension(80, 150));
        CommunityChest1.setPreferredSize(new java.awt.Dimension(79, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        south.add(CommunityChest1, gridBagConstraints);

        Baltic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/baltic.jpg"))); // NOI18N
        Baltic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Baltic.setMaximumSize(new java.awt.Dimension(80, 150));
        Baltic.setMinimumSize(new java.awt.Dimension(80, 150));
        Baltic.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        south.add(Baltic, gridBagConstraints);

        IncomeTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/incometax.jpg"))); // NOI18N
        IncomeTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IncomeTax.setMaximumSize(new java.awt.Dimension(80, 150));
        IncomeTax.setMinimumSize(new java.awt.Dimension(80, 150));
        IncomeTax.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        south.add(IncomeTax, gridBagConstraints);

        Reading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/reading.jpg"))); // NOI18N
        Reading.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Reading.setMaximumSize(new java.awt.Dimension(80, 150));
        Reading.setMinimumSize(new java.awt.Dimension(80, 150));
        Reading.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        south.add(Reading, gridBagConstraints);

        Oriental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/oriental.jpg"))); // NOI18N
        Oriental.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Oriental.setMaximumSize(new java.awt.Dimension(80, 150));
        Oriental.setMinimumSize(new java.awt.Dimension(80, 150));
        Oriental.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        south.add(Oriental, gridBagConstraints);

        Chance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/chance1.jpg"))); // NOI18N
        Chance1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Chance1.setMaximumSize(new java.awt.Dimension(80, 150));
        Chance1.setMinimumSize(new java.awt.Dimension(80, 150));
        Chance1.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        south.add(Chance1, gridBagConstraints);

        Vermont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/vermont.jpg"))); // NOI18N
        Vermont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Vermont.setMaximumSize(new java.awt.Dimension(80, 150));
        Vermont.setMinimumSize(new java.awt.Dimension(80, 150));
        Vermont.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        south.add(Vermont, gridBagConstraints);

        Connecticut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/connecticut.jpg"))); // NOI18N
        Connecticut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Connecticut.setMaximumSize(new java.awt.Dimension(80, 150));
        Connecticut.setMinimumSize(new java.awt.Dimension(80, 150));
        Connecticut.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        south.add(Connecticut, gridBagConstraints);

        Board.add(south, java.awt.BorderLayout.PAGE_END);

        west.setBackground(java.awt.Color.darkGray);
        west.setBorder(null);
        west.setMaximumSize(new java.awt.Dimension(175, 870));
        west.setName("west"); // NOI18N
        west.setPreferredSize(new java.awt.Dimension(150, 720));
        west.setLayout(new java.awt.GridBagLayout());

        Tenessee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/tenessee.jpg"))); // NOI18N
        Tenessee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tenessee.setMaximumSize(new java.awt.Dimension(150, 78));
        Tenessee.setMinimumSize(new java.awt.Dimension(150, 78));
        Tenessee.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        west.add(Tenessee, gridBagConstraints);

        CommunityChest2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/communitychesteast.jpg"))); // NOI18N
        CommunityChest2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CommunityChest2.setMaximumSize(new java.awt.Dimension(150, 78));
        CommunityChest2.setMinimumSize(new java.awt.Dimension(150, 78));
        CommunityChest2.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        west.add(CommunityChest2, gridBagConstraints);

        James.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/james.jpg"))); // NOI18N
        James.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        James.setMaximumSize(new java.awt.Dimension(150, 78));
        James.setMinimumSize(new java.awt.Dimension(150, 78));
        James.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        west.add(James, gridBagConstraints);

        PennisylvaniaRR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/pennsylvania.jpg"))); // NOI18N
        PennisylvaniaRR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PennisylvaniaRR.setMaximumSize(new java.awt.Dimension(150, 78));
        PennisylvaniaRR.setMinimumSize(new java.awt.Dimension(150, 78));
        PennisylvaniaRR.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        west.add(PennisylvaniaRR, gridBagConstraints);

        States.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/states.jpg"))); // NOI18N
        States.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        States.setMaximumSize(new java.awt.Dimension(150, 78));
        States.setMinimumSize(new java.awt.Dimension(150, 78));
        States.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        west.add(States, gridBagConstraints);

        Virginia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/virginia.jpg"))); // NOI18N
        Virginia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Virginia.setMaximumSize(new java.awt.Dimension(150, 78));
        Virginia.setMinimumSize(new java.awt.Dimension(150, 78));
        Virginia.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        west.add(Virginia, gridBagConstraints);

        Electric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/electric.jpg"))); // NOI18N
        Electric.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Electric.setMaximumSize(new java.awt.Dimension(150, 78));
        Electric.setMinimumSize(new java.awt.Dimension(150, 78));
        Electric.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        west.add(Electric, gridBagConstraints);

        Charles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/charles.jpg"))); // NOI18N
        Charles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Charles.setMaximumSize(new java.awt.Dimension(150, 78));
        Charles.setMinimumSize(new java.awt.Dimension(150, 78));
        Charles.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        west.add(Charles, gridBagConstraints);

        NewYork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/newyork.jpg"))); // NOI18N
        NewYork.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NewYork.setMaximumSize(new java.awt.Dimension(150, 78));
        NewYork.setMinimumSize(new java.awt.Dimension(150, 78));
        NewYork.setPreferredSize(new java.awt.Dimension(150, 80));
        west.add(NewYork, new java.awt.GridBagConstraints());

        Board.add(west, java.awt.BorderLayout.WEST);

        east.setBackground(java.awt.Color.darkGray);
        east.setName("east"); // NOI18N
        east.setPreferredSize(new java.awt.Dimension(150, 720));
        east.setRequestFocusEnabled(false);
        east.setLayout(new java.awt.GridBagLayout());

        Pacific.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/pacific.jpg"))); // NOI18N
        Pacific.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pacific.setPreferredSize(new java.awt.Dimension(150, 80));
        east.add(Pacific, new java.awt.GridBagConstraints());

        NorthCarolina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/ncarolina.jpg"))); // NOI18N
        NorthCarolina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NorthCarolina.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        east.add(NorthCarolina, gridBagConstraints);

        CommunityChest3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/communitychestwest.jpg"))); // NOI18N
        CommunityChest3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CommunityChest3.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        east.add(CommunityChest3, gridBagConstraints);

        Pennisylvania.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/pennisylviania.jpg"))); // NOI18N
        Pennisylvania.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pennisylvania.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        east.add(Pennisylvania, gridBagConstraints);

        Short.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/sortline.jpg"))); // NOI18N
        Short.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Short.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        east.add(Short, gridBagConstraints);

        Chance3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/chancewest.jpg"))); // NOI18N
        Chance3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Chance3.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        east.add(Chance3, gridBagConstraints);

        ParkPlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/parkplace.jpg"))); // NOI18N
        ParkPlace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ParkPlace.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        east.add(ParkPlace, gridBagConstraints);

        LuxuryTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/tax.jpg"))); // NOI18N
        LuxuryTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LuxuryTax.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        east.add(LuxuryTax, gridBagConstraints);

        Boardwalk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/boardwalk.jpg"))); // NOI18N
        Boardwalk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Boardwalk.setPreferredSize(new java.awt.Dimension(150, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        east.add(Boardwalk, gridBagConstraints);

        Board.add(east, java.awt.BorderLayout.LINE_END);

        center.setName("center"); // NOI18N
        center.setLayout(new java.awt.CardLayout());

        centerBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/monopoly.jpg"))); // NOI18N
        center.add(centerBoard, "card2");

        Board.add(center, java.awt.BorderLayout.CENTER);

        north.setBackground(java.awt.Color.darkGray);
        north.setBorder(null);
        north.setName("north"); // NOI18N
        north.setPreferredSize(new java.awt.Dimension(1020, 150));
        north.setLayout(new java.awt.GridBagLayout());

        FreeParking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/freeparking.jpg"))); // NOI18N
        FreeParking.setBorder(null);
        FreeParking.setBorderPainted(false);
        FreeParking.setMaximumSize(new java.awt.Dimension(150, 150));
        FreeParking.setMinimumSize(new java.awt.Dimension(150, 150));
        FreeParking.setPreferredSize(new java.awt.Dimension(150, 150));
        north.add(FreeParking, new java.awt.GridBagConstraints());

        GoToJail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/gotojail.jpg"))); // NOI18N
        GoToJail.setBorder(null);
        GoToJail.setBorderPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        north.add(GoToJail, gridBagConstraints);

        Kentucky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/kentucky.jpg"))); // NOI18N
        Kentucky.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Kentucky.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        north.add(Kentucky, gridBagConstraints);

        Chance2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/chancenorth.jpg"))); // NOI18N
        Chance2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Chance2.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        north.add(Chance2, gridBagConstraints);

        Indiana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/indiana.jpg"))); // NOI18N
        Indiana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Indiana.setPreferredSize(new java.awt.Dimension(80, 150));
        north.add(Indiana, new java.awt.GridBagConstraints());

        Illonois.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/illonios.jpg"))); // NOI18N
        Illonois.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Illonois.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        north.add(Illonois, gridBagConstraints);

        BO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/bo.jpg"))); // NOI18N
        BO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BO.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        north.add(BO, gridBagConstraints);

        Atlantic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/atlantic.jpg"))); // NOI18N
        Atlantic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Atlantic.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        north.add(Atlantic, gridBagConstraints);

        Marvin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/marvin.jpg"))); // NOI18N
        Marvin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Marvin.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        north.add(Marvin, gridBagConstraints);

        WaterWorks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/waterworks.jpg"))); // NOI18N
        WaterWorks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        WaterWorks.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        north.add(WaterWorks, gridBagConstraints);

        Ventinor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/gui/img/grid/ventinor.jpg"))); // NOI18N
        Ventinor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ventinor.setPreferredSize(new java.awt.Dimension(80, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        north.add(Ventinor, gridBagConstraints);

        Board.add(north, java.awt.BorderLayout.PAGE_START);

        Layers.add(Board);
        Board.setBounds(0, 0, 1020, 1020);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(Layers, gridBagConstraints);

        Menu.setBackground(new java.awt.Color(223, 233, 229));
        Menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        Menu.setMaximumSize(new java.awt.Dimension(300, 1020));
        Menu.setMinimumSize(new java.awt.Dimension(300, 1020));
        Menu.setPreferredSize(new java.awt.Dimension(300, 1020));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(0, 5, 20);
        flowLayout1.setAlignOnBaseline(true);
        Menu.setLayout(flowLayout1);
        getContentPane().add(Menu, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     */
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atlantic;
    private javax.swing.JButton BO;
    private javax.swing.JButton Baltic;
    private javax.swing.JPanel Board;
    private javax.swing.JButton Boardwalk;
    private javax.swing.JButton Chance1;
    private javax.swing.JButton Chance2;
    private javax.swing.JButton Chance3;
    private javax.swing.JButton Charles;
    private javax.swing.JButton CommunityChest1;
    private javax.swing.JButton CommunityChest2;
    private javax.swing.JButton CommunityChest3;
    private javax.swing.JButton Connecticut;
    private javax.swing.JButton Die1;
    private javax.swing.JButton Die2;
    private javax.swing.JButton Electric;
    private javax.swing.JButton FreeParking;
    private javax.swing.JButton Go;
    private javax.swing.JButton GoToJail;
    private javax.swing.JButton Illonois;
    private javax.swing.JButton IncomeTax;
    private javax.swing.JButton Indiana;
    private javax.swing.JButton Jail;
    private javax.swing.JButton James;
    private javax.swing.JButton Kentucky;
    private javax.swing.JLayeredPane Layers;
    private javax.swing.JButton LuxuryTax;
    private javax.swing.JButton Marvin;
    private javax.swing.JButton Mediterranean;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton NewYork;
    private javax.swing.JButton NorthCarolina;
    private javax.swing.JPanel Objects;
    private javax.swing.JButton Oriental;
    private javax.swing.JButton Pacific;
    private javax.swing.JButton ParkPlace;
    private javax.swing.JButton Pennisylvania;
    private javax.swing.JButton PennisylvaniaRR;
    private javax.swing.JButton Reading;
    private javax.swing.JButton Short;
    private javax.swing.JButton States;
    private javax.swing.JButton Tenessee;
    private javax.swing.JButton Ventinor;
    private javax.swing.JButton Vermont;
    private javax.swing.JButton Virginia;
    private javax.swing.JButton WaterWorks;
    private javax.swing.JPanel center;
    private javax.swing.JLabel centerBoard;
    private javax.swing.JPanel east;
    private javax.swing.JPanel north;
    private javax.swing.JPanel south;
    private javax.swing.JPanel west;
    // End of variables declaration//GEN-END:variables
}
